enum Department : String, CaseIterable {
  case automotive = "Automotive"
  case baby = "Baby"
  case beauty = "Beauty"
  case books = "Books"
  case clothing = "Clothing"
  case computers = "Computers"
  case electronics = "Electronics"
  case games = "Games"
  case garden = "Garden"
  case grocery = "Grocery"
  case health = "Health"
  case home = "Home"
  case industrial = "Industrial"
  case jewelry = "Jewelry"
  case kids = "Kids"
  case movies = "Movies"
  case music = "Music"
  case outdoors = "Outdoors"
  case shoes = "Shoes"
  case sports = "Sports"
  case toys = "Toys"
}
